### ISSUE TITLE
Have link to manydecks open in new tab

### ISSUE THREAD

**Issue by StefKirsch** [ubvu/OpenScienceAgainstHumanity#2]
See [here](https://www.eddymens.com/blog/how-to-make-a-markdown-link-open-in-another-tab#:~:text=You%20just%20add%20the%20target,in%20a%20different%20browser%20tab.&text=The%20only%20downside%20to%20this,depending%20on%20your%20use%20case.)

**Comment by vansteph** [comment]
I close this issue now as we tried to make it work, but it doesn't somehow. See our decision to close this issue in our teams channel.
